### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [Hypsurus/skod#5]
Would you like to add more error handling for return values from functions like the following?
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output.") ⇒ [skod_parse_stat](https://github.com/Hypsurus/skod/blob/369c643d0078c5571fd5413eb3e288fdad967a12/src/skod.c#L59)
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "Reposition a file-position indicator.") ⇒ [ftp_upload_single](https://github.com/Hypsurus/skod/blob/e49bb8a81acc95a67ba29cd24c9cad085409048e/src/ftp.c#L55)

**Comment by Hypsurus** [comment]
Hello @elfring first of all thank you! :smile: 
Can you send PR for #4 and #5?

**Comment by Hypsurus** [comment]
I working on it

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?
