### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [Hypsurus/skod#6]
The function "[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html "Terminate a process.")" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function "[signal_handler](https://github.com/Hypsurus/skod/blob/c75016d4f63650f9f6fc6be9c6893eea5f4971ab/src/utils.c#L57 "Reconsider signal handling implementation.")".

**Comment by Hypsurus** [comment]
Thanks for that! I will fix this. Maybe void return; will do the job?
We want to quit when the user press ctrl+c.

**Comment by elfring** [comment]
Would you like to consider other software design options?
* [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "wait for queued signals")
* [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
* [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")

**Comment by Hypsurus** [comment]
Yes sure , I will work on this.

**Comment by elfring** [comment]
Should this issue be kept open until the affected implementation details will be fixed?
